### ISSUE TITLE
Issue with Craft 5 migration

### ISSUE THREAD

**Issue by timmyomahony** [weareferal/craft-matrix-field-preview#130]
(I've moved this issue from https://github.com/timmyomahony/craft-matrix-field-preview/issues/126#issuecomment-2277765343, from @irategod)

> Hi, thanks for continuing to work on this plugin and getting a Craft 5 release ready.
When upgrading one of our client's sites to Craft 5, on my local version, running `php craft up` produces an error when applying the appropriate migration. I've attached the stack trace below, let me know if you require any further input from me.

```*** applying m240804_214123_converted_blocktype_to_entrytype
    > add foreign key fk_iysiarioivogkjyoklqmzmivqniiyaatmldy: {{%matrixfieldpreview_blocktypes_config}} (blockTypeId) references {{%entrytypes}} (id) ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`#sql-alter-1-90`, CONSTRAINT `fk_iysiarioivogkjyoklqmzmivqniiyaatmldy` FOREIGN KEY (`blockTypeId`) REFERENCES `entrytypes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
The SQL being executed was: ALTER TABLE `matrixfieldpreview_blocktypes_config` ADD CONSTRAINT `fk_iysiarioivogkjyoklqmzmivqniiyaatmldy` FOREIGN KEY (`blockTypeId`) REFERENCES `entrytypes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ma...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE `ma...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(478): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(436): yii\db\Migration->addForeignKey('fk_iysiarioivog...', '{{%matrixfieldp...', 'blockTypeId', '{{%entrytypes}}', 'id', 'CASCADE', 'CASCADE')
#4 /var/www/html/vendor/weareferal/matrix-field-preview/src/migrations/m240804_214123_converted_blocktype_to_entrytype.php(19): craft\db\Migration->addForeignKey('fk_iysiarioivog...', '{{%matrixfieldp...', 'blockTypeId', '{{%entrytypes}}', 'id', 'CASCADE', 'CASCADE')
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): weareferal\matrixfieldpreview\migrations\m240804_214123_converted_blocktype_to_entrytype->safeUp()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240804_214123_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#12 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#18 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#19 [internal function]: craft\console\controllers\UpController->actionIndex()
#20 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#22 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#23 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#25 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#26 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#27 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#28 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#29 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#30 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#31 /var/www/html/craft(13): yii\base\Application->run()
#32 {main}
*** failed to apply m240804_214123_converted_blocktype_to_entrytype (time: 0.041s)```

_Originally posted by @IrateGod in https://github.com/timmyomahony/craft-matrix-field-preview/issues/126#issuecomment-2277765343_

**Comment by timmyomahony** [comment]
@irategod could you let me know what version of Craft CMS you're using (latest 5.3 or just 5.0)? Also what database and version you are using?

**Comment by mofman** [comment]
```
    *** applying m240804_214123_converted_blocktype_to_entrytype
        > add foreign key craft_fk_axvvhfpqmualjuozugpbtbrprysdewbllwbe: {{%matrixfieldpreview_blocktypes_config}} (blockTypeId) references {{%entrytypes}} (id) ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`craft_equalityni`.`#sql-alter-e42f-6fb`, CONSTRAINT `craft_fk_axvvhfpqmualjuozugpbtbrprysdewbllwbe` FOREIGN KEY (`blockTypeId`) REFERENCES `craft_entrytypes` (`id`) ON DELETE CASCADE ON UPDAT)
    The SQL being executed was: ALTER TABLE `craft_matrixfieldpreview_blocktypes_config` ADD CONSTRAINT `craft_fk_axvvhfpqmualjuozugpbtbrprysdewbllwbe` FOREIGN KEY (`blockTypeId`) REFERENCES `craft_entrytypes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE (/Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/db/Schema.php:676)
    #0 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
    #1 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE `cr...')
    #2 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/db/Migration.php(478): yii\db\Command->execute()
    #3 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/db/Migration.php(454): yii\db\Migration->addForeignKey('craft_fk_axvvhf...', '{{%matrixfieldp...', 'blockTypeId', '{{%entrytypes}}', 'id', 'CASCADE', 'CASCADE')
    #4 /Users/andrew/Sites/equality-commission-ni/vendor/weareferal/matrix-field-preview/src/migrations/m240804_214123_converted_blocktype_to_entrytype.php(19): craft\db\Migration->addForeignKey('craft_fk_axvvhf...', '{{%matrixfieldp...', 'blockTypeId', '{{%entrytypes}}', 'id', 'CASCADE', 'CASCADE')
    #5 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/db/Migration.php(50): weareferal\matrixfieldpreview\migrations\m240804_214123_converted_blocktype_to_entrytype->safeUp()
    #6 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
    #7 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240804_214123_...')
    #8 [internal function]: craft\console\controllers\MigrateController->actionAll()
    #9 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
    #10 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
    #11 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
    #12 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
    #13 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
    #14 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
    #15 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
    #16 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
    #17 /Users/andrew/Sites/equality-commission-ni/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
    #18 /Users/andrew/Sites/equality-commission-ni/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
    #19 /Users/andrew/Sites/equality-commission-ni/craft(13): yii\base\Application->run()
    #20 {main}
```

Happening for us to: Craft 5.3

**Comment by timmyomahony** [comment]
Thanks @mofman to confirm:

- You previously had the Craft 4 version installed
- You upgraded to Craft 5 and disabled the plugin (I assume)
- You are now upgrading the plugin to the new Craft 5 version

Could you also let me know what DB you're using and version?

**Comment by mofman** [comment]
No problem,

* The site was running Craft 4.11.3 along with Matrix Field Preview 4.1.4
* Yes I updated all the dependencies including matrix-preview in the composer.json file and then ran composer update
* Upon running ./craft migrate/all is where I experienced the error
* Using MariaDB 11.4.2
* Also tried Craft CMS 5.2 to see if i had any effect which it didnt

**Comment by stevethitchman** [comment]
@timmyomahony I experienced this exact issue and because this ultimately deletes the records in the table it's modifying I cleared that table first and then the migration ran without any problems so I suspect just re-ordering the logic here would solve this issue.

**Comment by mmcbride2929** [comment]
Was this ever fixed? Performing a craft 5 upgrade and still experiencing this. Thanks! MySql 8, craft 4->5.8. @timmyomahony

**Comment by philippe-leeroy** [comment]
I encountered the same error, and to fix it, I directly modified the matrixfieldpreview_neo_blocktypes_config and matrixfieldpreview_blocktypes_config tables, deleting rows under two conditions:

1. When "blockTypeId" is null.
2. When "blockTypeId" doesn't have a corresponding "id" in the "entrytypes" table.

Hope this helps!

**Comment by twitcher07** [comment]
I experienced this same migration error going from Craft 4 to Craft 5 on a site. Following @philippe-leeroy suggestion worked for me. Except I only had a table for `matrixfieldpreview_blocktypes_config` that contained rows with blockTypeId that didn't have a corresponding Id in entrytypes.

However, it would be nice to have an official patch for this issue.

**Comment by timmyomahony** [comment]
I've tried a number of times to replicate this issue by doing Craft 4 -> 5 upgrades, but I've not been able to encounter it. That said, I believe I understand what the issue is so I've tried to clean up the migration so that it potentially doesn't throw the error:

https://github.com/timmyomahony/craft-matrix-field-preview/releases/tag/5.3.5

I'm going to leave this issue open for a little while in case anyone else encounters it (or doesn't)

**Comment by IrateGod** [comment]
Hi @timmyomahony -- as it so happens, I am just again in the same upgrade process encountering the same issue with 5.3.0, however after revisiting this issue (sorry, I totally catch the tag on GH!) and upgrading to 5.3.5 the migration no longer fails.

**Comment by timmyomahony** [comment]
OK great, so it sounds like the issue should be fixed?

**Comment by timmyomahony** [comment]
I'm closing this but if anyone else encounters it please get in touch
